In [ ]:
import numpy as np

n = 4
X = np.array(range(1, n+1))
# Hàm tính dấu của hoán vị (sign of permutation)
def sgn_by_def(sigma):
    ket_qua = 1.0
    for i in range(len(X) - 1):
        for j in range(i + 1, len(X)):
            ket_qua = ket_qua * ((X[i] - X[j]) / (sigma[i] - sigma[j]))
    return int(ket_qua)

# Kiểm tra các ví dụ trong đề
sigma = np.array([2, 1, 3, 4])
print(sgn_by_def(sigma))  # Kết quả: -1

sigma = np.array([1, 2, 3, 4])
print(sgn_by_def(sigma))  # Kết quả: 1

sigma = np.array([4, 3, 2, 1])
print(sgn_by_def(sigma))  # Kết quả: 1


-1
1
1


In [ ]:
from itertools import permutations
import numpy as np

# Hàm tính dấu hoán vị (sgn)
def sgn_by_def(sigma):
    X = np.array(range(1, len(sigma)+1))
    ket_qua = 1.0
    for i in range(len(X) - 1):
        for j in range(i + 1, len(X)):
            ket_qua *= (X[i] - X[j]) / (sigma[i] - sigma[j])
    return int(ket_qua)

# Hàm phát sinh biểu thức định thức
def phatsinh_dinhthuc(n):
    X = [i for i in range(1, n+1)]
    Sn = list(permutations(X))
    dinhthuc = ""

    for sn in Sn:
        sigma = np.array(sn)
        product = ""
        for i in range(1, n + 1):
            product += "a" + str(i) + str(sn[i - 1])

        dau = sgn_by_def(sigma)
        if dau != 1:
            product = "- " + product
        else:
            product = "+ " + product

        dinhthuc += product + " "

    return dinhthuc.strip()

# In kết quả ra màn hình
print("Định thức cấp 2 là:")
print(phatsinh_dinhthuc(2))

print("\nĐịnh thức cấp 3 là:")
print(phatsinh_dinhthuc(3))


Định thức cấp 2 là:
+ a11a22 - a12a21

Định thức cấp 3 là:
+ a11a22a33 - a11a23a32 - a12a21a33 + a12a23a31 + a13a21a32 - a13a22a31


In [ ]:
import numpy as np
import math
from itertools import permutations

# Hàm tính dấu hoán vị
def sgn_by_def(sigma):
    X = np.array(range(1, len(sigma)+1))
    ket_qua = 1.0
    for i in range(len(X) - 1):
        for j in range(i + 1, len(X)):
            ket_qua *= (X[i] - X[j]) / (sigma[i] - sigma[j])
    return int(ket_qua)

# Hàm tính giá trị định thức của ma trận A
def tinhtoan_dinhthuc(A):
    X = []
    n = int(math.sqrt(A.size))  # Tính kích thước ma trận
    for i in range(1, n + 1):
        X.append(i)

    Sn = list(permutations(X))
    dinhthuc = 0

    for sn in Sn:
        sigma = np.array(sn)
        product = 1
        for i in range(1, n + 1):
            product *= A[i - 1][sn[i - 1] - 1]  # Nhân các phần tử theo hoán vị
        dau = sgn_by_def(sigma)
        dinhthuc += dau * product

    return dinhthuc

# Khai báo ma trận A
A = np.array([[3, 5, -8], [4, 12, -1], [2, 5, 3]])

# In kết quả định thức ra màn hình
print("Giá trị định thức của ma trận A là:", tinhtoan_dinhthuc(A))


Giá trị định thức của ma trận A là: 85


In [ ]:
import numpy as np
import math
from itertools import permutations
from scipy import linalg

# Hàm tính dấu hoán vị
def sgn_by_def(sigma):
    X = np.array(range(1, len(sigma)+1))
    ket_qua = 1.0
    for i in range(len(X) - 1):
        for j in range(i + 1, len(X)):
            ket_qua *= (X[i] - X[j]) / (sigma[i] - sigma[j])
    return int(ket_qua)

# Hàm tự viết tính định thức
def tinhtoan_dinhthuc(A):
    n = int(math.sqrt(A.size))  # Ma trận vuông cấp n
    X = list(range(1, n + 1))
    Sn = list(permutations(X))
    dinhthuc = 0

    for sn in Sn:
        sigma = np.array(sn)
        product = 1
        for i in range(1, n + 1):
            product *= A[i - 1][sn[i - 1] - 1]
        dau = sgn_by_def(sigma)
        dinhthuc += dau * product

    return dinhthuc

# Hệ phương trình:
# 4x - 2y = 10
# 3x - 5y = 11

# Khai báo các ma trận
A = np.array([[4, -2], [3, -5]])
A1 = np.array([[10, -2], [11, -5]])
A2 = np.array([[4, 10], [3, 11]])

# Tính bằng scipy
detA_sci = linalg.det(A)
detA1_sci = linalg.det(A1)
detA2_sci = linalg.det(A2)

print("➡ Kết quả bằng scipy.linalg.det():")
print("detA  =", detA_sci)
print("detA1 =", detA1_sci)
print("detA2 =", detA2_sci)

if detA_sci != 0:
    x1 = detA1_sci / detA_sci
    x2 = detA2_sci / detA_sci
    print("→ Nghiệm hệ phương trình là: x1 =", x1, ", x2 =", x2)
else:
    print("→ Hệ phương trình vô nghiệm hoặc vô số nghiệm.")

# Tính bằng hàm tự viết
detA_tu = tinhtoan_dinhthuc(A)
detA1_tu = tinhtoan_dinhthuc(A1)
detA2_tu = tinhtoan_dinhthuc(A2)

print("\n➡ Kết quả bằng tinhtoan_dinhthuc():")
print("detA  =", detA_tu)
print("detA1 =", detA1_tu)
print("detA2 =", detA2_tu)


➡ Kết quả bằng scipy.linalg.det():
detA  = -14.0
detA1 = -28.0
detA2 = 14.000000000000004
→ Nghiệm hệ phương trình là: x1 = 2.0 , x2 = -1.0000000000000002

➡ Kết quả bằng tinhtoan_dinhthuc():
detA  = -14
detA1 = -28
detA2 = 14


In [ ]:
import numpy as np
from scipy import linalg
from itertools import permutations

# Hàm tính dấu hoán vị
def sgn_by_def(sigma):
    X = np.array(range(1, len(sigma)+1))
    ket_qua = 1.0
    for i in range(len(X) - 1):
        for j in range(i + 1, len(X)):
            ket_qua *= (X[i] - X[j]) / (sigma[i] - sigma[j])
    return int(ket_qua)

# Hàm tự viết tính định thức
def tinhtoan_dinhthuc(A):
    n = int(np.sqrt(A.size))
    X = list(range(1, n + 1))
    Sn = list(permutations(X))
    dinhthuc = 0
    for sn in Sn:
        sigma = np.array(sn)
        product = 1
        for i in range(1, n + 1):
            product *= A[i - 1][sn[i - 1] - 1]
        dau = sgn_by_def(sigma)
        dinhthuc += dau * product
    return dinhthuc

# Khai báo các ma trận
A = np.array([[1, 2, -3],
              [2, -2, 1],
              [3, -4, 4]])

X = np.array([[1, 2, -3],
              [3, -2, 1],
              [2, -4, 4]])

Y = np.array([[1, 1, -3],
              [2, 3, 1],
              [3, 2, 4]])

Z = np.array([[1, 2, 1],
              [2, -2, 3],
              [3, -4, 2]])

# ===== PHƯƠNG PHÁP 1: DÙNG scipy.linalg.det() =====
detA = linalg.det(A)
detX = linalg.det(X)
detY = linalg.det(Y)
detZ = linalg.det(Z)

x, y, z = detX / detA, detY / detA, detZ / detA
print("→ Kết quả dùng scipy.linalg.det():")
print("x =", x, "y =", y, "z =", z)

# ===== PHƯƠNG PHÁP 2: DÙNG tinhtoan_dinhthuc() =====
detA2 = tinhtoan_dinhthuc(A)
detX2 = tinhtoan_dinhthuc(X)
detY2 = tinhtoan_dinhthuc(Y)
detZ2 = tinhtoan_dinhthuc(Z)

x2, y2, z2 = detX2 / detA2, detY2 / detA2, detZ2 / detA2
print("\n→ Kết quả dùng tinhtoan_dinhthuc():")
print("x =", x2, "y =", y2, "z =", z2)


→ Kết quả dùng scipy.linalg.det():
x = -0.0 y = -2.500000000000001 z = -2.000000000000001

→ Kết quả dùng tinhtoan_dinhthuc():
x = -0.0 y = -2.5 z = -2.0


In [ ]:
import numpy as np

def cofactor_matrix(A):
    n = A.shape[0]
    cof = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            minor = np.delete(np.delete(A, i, axis=0), j, axis=1)
            cof[i, j] = ((-1) ** (i + j)) * np.linalg.det(minor)
    return cof

def adjoint_matrix(A):
    return cofactor_matrix(A).T

# Ma trận ví dụ
A = np.array([[2, 1, 3],
              [1, 0, 2],
              [4, 1, 8]])

cof = cofactor_matrix(A)
adj = adjoint_matrix(A)

print("Ma trận hệ số kép:")
print(cof)

print("\nMa trận liên hợp:")
print(adj)


Ma trận hệ số kép:
[[-2. -0.  1.]
 [-5.  4.  2.]
 [ 2. -1. -1.]]

Ma trận liên hợp:
[[-2. -5.  2.]
 [-0.  4. -1.]
 [ 1.  2. -1.]]


In [ ]:
import sympy as sp

# Khai báo biến
x, y = sp.symbols('x y')

# Ba điểm bất kỳ trên đường tròn
P1 = (1, 1)
P2 = (2, 4)
P3 = (5, 3)

# Hàm tạo 1 hàng của ma trận từ 1 điểm
def circle_row(x0, y0):
    return [x0**2 + y0**2, x0, y0, 1]

# Ma trận 4x4 để tính định thức
M = sp.Matrix([
    circle_row(P1[0], P1[1]),
    circle_row(P2[0], P2[1]),
    circle_row(P3[0], P3[1]),
    circle_row(x, y)
])

# Tính định thức và phương trình đường tròn
det = M.det()
circle_eq = sp.Eq(det, 0)

# In phương trình đường tròn
print("Phương trình đường tròn đi qua 3 điểm:")
sp.pprint(circle_eq)


Phương trình đường tròn đi qua 3 điểm:
    2              2                
10⋅x  - 60⋅x + 10⋅y  - 40⋅y + 80 = 0
