In [ ]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
tich = np.inner(a,b) # tích vô hướng
print (tich)
c =  np.dot(a,b)
print(c)

32
32


In [ ]:
import math
import numpy as np
from scipy import linalg

# Hàm chuẩn do bạn định nghĩa
def chuan(v, k):
    tong = 0
    for i in range(len(v)):
        tong += abs(v[i])**k
    ketqua = math.pow(tong, 1.0 / k)  # lấy căn bậc k
    return ketqua

# Khởi tạo vector
a = np.array([1, 2, -3])

# Các bậc chuẩn muốn kiểm tra
bac_list = [1, 2, 3, 1000]

print("Vector a:", a)
for k in bac_list:
    print(f"\nChuẩn bậc {k}:")
    print("  chuan(a, {}):".format(k), chuan(a, k))
    print("  np.linalg.norm(a, {}):".format(k), np.linalg.norm(a, k))
    print("  scipy.linalg.norm(a, {}):".format(k), linalg.norm(a, k))

# Thêm chuẩn mặc định (chuẩn 2)
print("\nChuẩn mặc định (norm 2):")
print("  scipy.linalg.norm(a):", linalg.norm(a))


Vector a: [ 1  2 -3]

Chuẩn bậc 1:
  chuan(a, 1): 6.0
  np.linalg.norm(a, 1): 6.0
  scipy.linalg.norm(a, 1): 6.0

Chuẩn bậc 2:
  chuan(a, 2): 3.7416573867739413
  np.linalg.norm(a, 2): 3.7416573867739413
  scipy.linalg.norm(a, 2): 3.7416573867739413

Chuẩn bậc 3:
  chuan(a, 3): 3.3019272488946263
  np.linalg.norm(a, 3): 3.3019272488946263
  scipy.linalg.norm(a, 3): 3.3019272488946263

Chuẩn bậc 1000:
  chuan(a, 1000): 1.0442214818467515
  np.linalg.norm(a, 1000): inf
  scipy.linalg.norm(a, 1000): inf

Chuẩn mặc định (norm 2):
  scipy.linalg.norm(a): 3.7416573867739413


/usr/local/lib/python3.11/dist-packages/numpy/linalg/_linalg.py:2780: RuntimeWarning: overflow encountered in power
  absx **= ord


In [ ]:
import numpy as np

# Khởi tạo dữ liệu
m = 10
v1 = np.array([5, -4, 3])
v2 = np.array([4, 3, -2])
v3 = np.array([-4, -3, -1])
v4 = np.array([-9, 8, 6])
mi = np.array([2, 5, 2, 1])
M = np.array([v1, v2, v3, v4])

# Ma trận chuyển vị
MT = M.transpose()
print("Ma trận chuyển vị MT:")
print(MT)

# Tính vector v = (1/m) * MT.dot(mi)
v = (1.0 / m) * MT.dot(mi)
print("\nVector v = (1/m) * MT.dot(mi):")
print(v)


Ma trận chuyển vị MT:
[[ 5  4 -4 -9]
 [-4  3 -3  8]
 [ 3 -2 -1  6]]

Vector v = (1/m) * MT.dot(mi):
[1.3 0.9 0. ]


In [ ]:
import sympy as sym
x, y = sym.symbols('x y')
xy = sym.Matrix([x,y]) # khai báo vector: (x, y)T
A = sym.Matrix([[1, -68],[1,1]])
v = sym.Matrix([0, 1])
nghiem = sym.solve([A*xy-v]) # phương trình được chuyển về 1 phía
print(sym.pretty(nghiem))

⎧   68         ⎫
⎨x: ──, y: 1/69⎬
⎩   69         ⎭


In [ ]:
import sympy
x, y, Lambda = sympy.symbols('x y Lambda')
I = sympy.eye(2)
A = sympy.Matrix([[2, 3], [3, -6]])
phuongtrinh = sympy.Eq(sympy.det(Lambda * I - A), 0)
nghiem = sympy.solve(phuongtrinh)
print([sympy.N(phantu, 4) for phantu in nghiem])
print (sympy.pretty(nghiem))


[-7.000, 3.000]
[-7, 3]


In [ ]:
import numpy as np
from numpy import linalg as LA

# Ma trận ban đầu
A = np.array([[2, 3], [3, -6]])
D = np.array([[-7, 0], [0, 3]])
P = np.array([[-1.0/3, 3], [1, 1]])

# 1. Tính nghịch đảo của P
P1 = LA.inv(P)
print("P^(-1):")
print(P1)

# 2. Kiểm tra A * P và P * D
print("\nA.dot(P):")
print(A.dot(P))

print("\nP.dot(D):")
print(P.dot(D))

# 3. Kiểm tra D ** 2
print("\nD ** 2:")
print(D @ D)  # tương đương với D ** 2

# 4. Tính A^1000 bằng công thức A^k = P D^k P^(-1)
A_1000 = P @ (D ** 1000) @ P1
print("\nA^1000 = P @ (D ** 1000) @ P^(-1):")
print(A_1000)


P^(-1):
[[-0.3  0.9]
 [ 0.3  0.1]]

A.dot(P):
[[ 2.33333333  9.        ]
 [-7.          3.        ]]

P.dot(D):
[[ 2.33333333  9.        ]
 [-7.          3.        ]]

D ** 2:
[[49  0]
 [ 0  9]]

A^1000 = P @ (D ** 1000) @ P^(-1):
[[ 5.03503397e+18  3.50482117e+18]
 [ 3.50482117e+18 -4.31115581e+18]]


In [ ]:
[Trắc nghiệm] Trong Python 3, các câu lệnh sau đây, câu lệnh nào tính chuẩn 2 của
vector a. Với a được xác định là:
>>> import numpy as np
>>> a = np.array([1,2,3])
a. >>> mag = np.sqrt(a.dot(a))
b. >>> mag = np.sqrt(a @ a )
c. >>> mag = np.sqrt(np.inner(a,a))
d. >>> mag = lambda x : math.sqrt(sum(i** 2 for i in x))
>>> mag(a)
a,b,c đúng

In [ ]:
import numpy as np

# Khởi tạo 2 vector u và v
u = np.array([1, 2, 3])   # bạn có thể thay bằng vector khác
v = np.array([4, 0, -1])  # vector khác

# Tính khoảng cách giữa 2 vector
distance = np.linalg.norm(u - v)

print("Khoảng cách giữa u và v là:", distance)


Khoảng cách giữa u và v là: 5.385164807134504


In [ ]:
import numpy as np

# Nhập 2 vector
u = np.array([float(x) for x in input("Nhập vector u (cách nhau bằng dấu cách): ").split()])
v = np.array([float(x) for x in input("Nhập vector v (cách nhau bằng dấu cách): ").split()])

# Tính tích vô hướng và độ dài 2 vector
dot_product = np.dot(u, v)
norm_u = np.linalg.norm(u)
norm_v = np.linalg.norm(v)

# Tính góc S bằng arccos
cos_theta = dot_product / (norm_u * norm_v)

# Chặn giá trị để tránh lỗi do làm tròn (giới hạn trong [-1, 1])
cos_theta = np.clip(cos_theta, -1.0, 1.0)

# Tính góc (đơn vị radian và độ)
theta_rad = np.arccos(cos_theta)
theta_deg = np.degrees(theta_rad)

print(f"Góc S giữa 2 vector (radian): {theta_rad}")
print(f"Góc S giữa 2 vector (độ): {theta_deg}")


Nhập vector u (cách nhau bằng dấu cách):  5 6 7
Nhập vector v (cách nhau bằng dấu cách): 7 8 9
Góc S giữa 2 vector (radian): 0.03354206928398118
Góc S giữa 2 vector (độ): 1.9218190061075167


In [ ]:
import numpy as np

# Nhập vector u và v
u = np.array([float(x) for x in input("Nhập vector u (cách nhau bằng dấu cách): ").split()])
v = np.array([float(x) for x in input("Nhập vector v (cách nhau bằng dấu cách): ").split()])

# Tính tích vô hướng và chuẩn bình phương của v
dot_uv = np.dot(u, v)
dot_vv = np.dot(v, v)

# Tính phép chiếu trực giao
projection = (dot_uv / dot_vv) * v

print("Phép chiếu trực giao của u lên v là:")
print(projection)


Nhập vector u (cách nhau bằng dấu cách): 4 7 8
Nhập vector v (cách nhau bằng dấu cách): 6 4 9
Phép chiếu trực giao của u lên v là:
[5.59398496 3.72932331 8.39097744]
