In [2]:
import numpy as np

# Tính ma trận A:
A = np.array([[0, 1], [1, 0]])
print(A)
temp = A.dot(A) # tính toan lần thứ 1
print(temp)

[[0 1]
 [1 0]]
[[1 0]
 [0 1]]


In [3]:
k= 6
for i in range(k-1):
  temp = temp.dot(A)
print (temp)
print('---')

[[0 1]
 [1 0]]
---


In [5]:
import numpy as np
B = np.array([ [0,-1], [-1,0]])
print(B)
emp = B.dot(B) # tính toan lần thứ 1
print(temp)

k= 5
for i in range(k-1):
  temp = temp.dot(B)
print (temp)
print('---')

[[ 0 -1]
 [-1  0]]
[[0 1]
 [1 0]]
[[0 1]
 [1 0]]
---


In [6]:
import numpy as np

# Khởi tạo ma trận C
C = np.array([
    [1, 0,   0],
    [0, 0.5, 1],
    [0, 0,   0.5]
])
print("Ma trận C:")
print(C)

# Lần nhân đầu tiên
temp = C.dot(C)
print("\nSau khi nhân lần 1 (C^2):")
print(temp)

# Nhân liên tiếp 1000 lần
k = 1000
for i in range(k - 1):
    temp = temp.dot(C)

print("\nSau khi nhân 1000 lần (gần W = C^1000):")
print(temp)

# Nhân tiếp 1000 lần nữa
for i in range(k - 1):
    temp = temp.dot(C)

print("\nSau khi nhân thêm 1000 lần nữa (gần C^2000):")
print(temp)


Ma trận C:
[[1.  0.  0. ]
 [0.  0.5 1. ]
 [0.  0.  0.5]]

Sau khi nhân lần 1 (C^2):
[[1.   0.   0.  ]
 [0.   0.25 1.  ]
 [0.   0.   0.25]]

Sau khi nhân 1000 lần (gần W = C^1000):
[[1.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 4.66631809e-302 9.34196882e-299]
 [0.00000000e+000 0.00000000e+000 4.66631809e-302]]

Sau khi nhân thêm 1000 lần nữa (gần C^2000):
[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
import numpy as np

# Ma trận M ban đầu
M = np.array([[0.8, 0.3],
              [0.2, 0.7]])

# M^2
MM = M.dot(M)
print("M^2:")
print(MM)

# M^3
MM = MM.dot(M)
print("\nM^3:")
print(MM)

# M^100
for i in range(100):
    MM = MM.dot(M)
print("\nM^103:")
print(MM)


M^2:
[[0.7  0.45]
 [0.3  0.55]]

M^3:
[[0.65  0.525]
 [0.35  0.475]]

M^103:
[[0.6 0.6]
 [0.4 0.4]]


In [8]:
import numpy as np

# Khởi tạo ma trận kề A
A = np.array([
    [0, 1, 0, 1],
    [0, 0, 1, 0],
    [1, 0, 0, 1],
    [1, 1, 0, 0]
])


sumA = A.copy()


temp = A.dot(A)
sumA = sumA + temp

k = 3
for i in range(1, k - 1):
    temp = temp.dot(A)
    sumA = sumA + temp

print("A^k (tức A^3):")
print(temp)

print("\nTổng các A^i từ i=1 đến i=k (k=3):")
print(sumA)


A^k (tức A^3):
[[1 1 1 2]
 [1 2 0 1]
 [1 2 2 1]
 [2 1 1 1]]

Tổng các A^i từ i=1 đến i=k (k=3):
[[2 3 2 3]
 [2 2 1 2]
 [3 4 2 3]
 [3 3 2 2]]


In [9]:
import numpy as np

# a. Chọn một ma trận khả nghịch 3x3
A = np.array([[2, 1, 1],
              [1, 3, 2],
              [1, 0, 0]])

# Kiểm tra ma trận có khả nghịch không (determinant khác 0)
det = np.linalg.det(A)
print("Định thức của A =", det)
if det == 0:
    print("Ma trận không khả nghịch!")
else:
    print("Ma trận khả nghịch.")

# b. Nhập họ tên hoặc MSSV
text = input("Nhập họ tên hoặc MSSV: ")

# c. Mã hóa: chuyển text thành số theo mã ASCII
# Ghép các số thành vector có bội số của 3
ascii_codes = [ord(ch) for ch in text]
while len(ascii_codes) % 3 != 0:
    ascii_codes.append(0)  # thêm số 0 để đủ chia hết cho 3

# Chuyển thành ma trận 3 hàng
matrix_input = np.array(ascii_codes).reshape(3, -1)
print("Dữ liệu số dạng ma trận:")
print(matrix_input)

# Mã hóa: nhân ma trận A
encoded = A.dot(matrix_input)
print("Dữ liệu sau khi mã hóa:")
print(encoded)

# d. Giải mã: nhân với ma trận nghịch đảo
A_inv = np.linalg.inv(A)
decoded_matrix = A_inv.dot(encoded)

# Làm tròn và chuyển về ký tự
decoded_flat = np.round(decoded_matrix).astype(int).flatten()
decoded_text = ''.join(chr(num) for num in decoded_flat if num > 0)

print("Dữ liệu sau khi giải mã:")
print(decoded_text)


Định thức của A = -1.0
Ma trận khả nghịch.
Nhập họ tên hoặc MSSV: 24432
Dữ liệu số dạng ma trận:
[[50 52]
 [52 51]
 [50  0]]
Dữ liệu sau khi mã hóa:
[[202 155]
 [306 205]
 [ 50  52]]
Dữ liệu sau khi giải mã:
24432


In [10]:
import numpy as np

def continued_fraction_to_fraction(seq):
    # Khởi tạo ma trận kết quả là ma trận đơn vị
    M = np.identity(2, dtype=object)

    # Duyệt chuỗi a0, a1, ..., an từ phải sang trái
    for a in reversed(seq):
        T = np.array([[a, 1], [1, 0]], dtype=object)
        M = np.dot(T, M)

    p_n = M[0][0]
    q_n = M[1][0]
    return p_n, q_n

# Thử nghiệm với ví dụ: 8/3 = [2, 1, 2]
seq = [2, 1, 2]
p, q = continued_fraction_to_fraction(seq)
print(f"Dãy liên phân số {seq} = {p}/{q}")


Dãy liên phân số [2, 1, 2] = 8/3
