In [3]:
import numpy as np

# Khởi tạo một mảng 2x2 gồm các ký tự
x = np.array([['a', 'b'], ['c', 'd']])
y = 'x'

# Dùng np.array với dtype=object để chứa các phần tử khác kiểu
C = np.array([[x, y], [1, 2]], dtype=object)
print("Ma trận C (kiểu object):")
print(C)

# Thử tạo np.matrix 3 chiều -> lỗi
try:
    A = np.matrix([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
except ValueError as e:
    print("\nLỗi khi tạo np.matrix 3 chiều:")
    print(e)

# Dùng np.array cho mảng 3 chiều (hợp lệ)
A = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("\nMảng 3 chiều A dùng np.array:")
print(A)


Ma trận C (kiểu object):
[[array([['a', 'b'],
         ['c', 'd']], dtype='<U1') 'x']
 [1 2]]

Lỗi khi tạo np.matrix 3 chiều:
matrix must be 2-dimensional

Mảng 3 chiều A dùng np.array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [5]:
import numpy as np

# Khởi tạo một mảng 2x2 gồm các ký tự
x = np.array([['a', 'b'], ['c', 'd']])
y = 'x'

# Dùng np.array với dtype=object để chứa các phần tử khác kiểu
C = np.array([[x, y], [1, 2]], dtype=object)
print("Ma trận C (kiểu object):")
print(C)

# Thử tạo np.matrix 3 chiều -> lỗi
try:
    A = np.matrix([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
except ValueError as e:
    print("\nLỗi khi tạo np.matrix 3 chiều:")
    print(e)

# Dùng np.array cho mảng 3 chiều (hợp lệ)
A = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("\nMảng 3 chiều A dùng np.array:")
print(A)


Ma trận C (kiểu object):
[[array([['a', 'b'],
         ['c', 'd']], dtype='<U1') 'x']
 [1 2]]

Lỗi khi tạo np.matrix 3 chiều:
matrix must be 2-dimensional

Mảng 3 chiều A dùng np.array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [6]:
from numpy import matlib

# Tạo ma trận đơn vị 5x5
G = matlib.identity(5)
print("Ma trận đơn vị G:")
print(G)

# Tạo ma trận ngẫu nhiên chuẩn (Gaussian) 3x2
H = matlib.randn(3, 2)
print("\nMa trận ngẫu nhiên H (chuẩn):")
print(H)

# Tạo ma trận toàn số 0 kích thước 4x4
K = matlib.zeros([4, 4])
print("\nMa trận toàn 0 K:")
print(K)


Ma trận đơn vị G:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Ma trận ngẫu nhiên H (chuẩn):
[[-0.46072506  0.13707185]
 [-2.20073436  0.08398972]
 [-0.46780922  0.20671004]]

Ma trận toàn 0 K:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
import numpy as np

# Dãy liên phân số để xấp xỉ số Pi
c = [3, 7, 15, 1, 292, 1, 1, 1, 2, 1, 3, 1, 14, 2]

# Khởi tạo ma trận đơn vị 2x2
M = np.asmatrix([[1, 0], [0, 1]])

# Lặp qua từng phần tử trong dãy để tính tích các ma trận
for i in range(len(c)):
    ci = np.asmatrix([[c[i], 1], [1, 0]])
    M = M @ ci  # hoặc M = M.dot(ci)

# In ma trận cuối cùng
print("Ma trận M:")
print(M)

# Tính số Pi xấp xỉ
pi_approx = M[0, 0] / M[1, 0]
print("\nGiá trị gần đúng của số Pi:")
print(pi_approx)


Ma trận M:
[[165707065  80143857]
 [ 52746197  25510582]]

Giá trị gần đúng của số Pi:
3.1415926535897936


In [9]:
import numpy as np

# Dữ liệu đầu vào
X = np.array([[1, 1], [1, 2], [1, 3], [1, 4], [1, 5]])  # Ma trận X (cột đầu toàn 1 cho hệ số a)
Y = np.array([[1.0], [2.0], [4.0], [4.0], [6.0]])      # Vector Y

# Tính X.T (chuyển vị của X)
XT = X.T

# Tính A1 = (X^T X)
A1 = XT.dot(X)

# Tính A2 = (X^T Y)
A2 = XT.dot(Y)

# Tính nghiệm A = (X^T X)^-1 * (X^T Y)
A = np.linalg.inv(A1).dot(A2)

# In phương trình hồi quy
print("Phương trình hồi quy: y = {:.3f} + {:.3f} * x".format(A[0, 0], A[1, 0]))

# Tính sai số tổng bình phương (residual sum of squares)
Y_pred = X.dot(A)
error = np.sum((Y - Y_pred)**2)
print("Tổng bình phương sai số:", round(error, 3))


Phương trình hồi quy: y = -0.200 + 1.200 * x
Tổng bình phương sai số: 0.8


In [12]:
import numpy as np
from numpy import linalg

def bpcuctieu(a):
    b = []       # chứa giá trị x (1, 2, 3, ...)
    o1 = []      # chứa toàn 1 (cho hệ số chặn)

    for i in range(len(a)):
        o1.append(1.0)
        b.append((i + 1) * 1.0)

    # Tạo ma trận X (2 x n)
    x = np.array([o1, b])
    print("Ma trận X:")
    print(x)

    # Tính U = X * X^T
    u = np.dot(x, x.T)
    print("\nMa trận U = X * X.T:")
    print(u)

    # Tính nghịch đảo của U
    u_1 = linalg.inv(u)
    print("\nNghịch đảo của U:")
    print(u_1)

    # Vector Y (dữ liệu thực tế)
    y = np.array(a)
    print("\nVector Y:")
    print(y)

    # Tính A = (X X^T)^(-1) X Y
    v = np.dot(u_1, x)
    A = np.dot(v, y)
    print("\nHệ số hồi quy A:")
    print(A)

    # Phương trình hồi quy tuyến tính
    print("\nPhương trình hồi quy:")
    print(f"y = {A[0]:.4f} + {A[1]:.4f} * x")

    # Dự đoán giá trị ngày kế tiếp (x = len(a)+1)
    next_x = len(a) + 1
    next_y = A[0] + A[1] * next_x
    print(f"\nDự đoán giá trị tại x = {next_x}: y = {next_y:.4f}")

    return A

# Ví dụ sử dụng
dulieu = [10.0, 8, 7, 5, 2]
bpcuctieu(dulieu)


Ma trận X:
[[1. 1. 1. 1. 1.]
 [1. 2. 3. 4. 5.]]

Ma trận U = X * X.T:
[[ 5. 15.]
 [15. 55.]]

Nghịch đảo của U:
[[ 1.1 -0.3]
 [-0.3  0.1]]

Vector Y:
[10.  8.  7.  5.  2.]

Hệ số hồi quy A:
[12.1 -1.9]

Phương trình hồi quy:
y = 12.1000 + -1.9000 * x

Dự đoán giá trị tại x = 6: y = 0.7000


array([12.1, -1.9])