In [1]:

import numpy as np

A = np.array([2, -1, 3, 0])
B = np.array([1, 4, -2, 5])

sum_AB = A + B
print("a)")
print("A + B =", sum_AB)

scalar_result = 3 * A - 2 * B
print("3A - 2B =", scalar_result)

a)
A + B = [3 3 1 5]
3A - 2B = [  4 -11  13 -10]


In [2]:
dot_product = np.dot(A, B)
norm_A = np.linalg.norm(A)
norm_B = np.linalg.norm(B)
cos_theta = dot_product / (norm_A * norm_B)
angle_deg = np.degrees(np.arccos(cos_theta))

print("\nb)")
print("A · B =", dot_product)
print("Góc giữa A và B (độ) =", round(angle_deg, 3))



b)
A · B = -8
Góc giữa A và B (độ) = 108.376


In [3]:
C = np.array([
    [1, 2, -1],
    [0, 3, 4],
    [2, -1, 0]
])

C_T = C.T
CTC = np.dot(C_T, C)

print("\nc)")
print("C^T * C =\n", CTC)


c)
C^T * C =
 [[ 5  0 -1]
 [ 0 14 10]
 [-1 10 17]]


In [4]:
import numpy as np

M = np.array([
    [1, 2, 3, 0],
    [4, 5, 6, 1],
    [7, 8, 9, 2],
    [0, 1, 1, 0]
])

N = np.array([
    [0, 1, 2, 3],
    [4, 5, 6, 7],
    [8, 9, 10, 11],
    [12, 13, 14, 15]
])

product = np.dot(M, N)
print("a)")
print("M × N =\n", product)



a)
M × N =
 [[ 32  38  44  50]
 [ 80  96 112 128]
 [128 154 180 206]
 [ 12  14  16  18]]


In [5]:
if M.shape[0] == M.shape[1]:
    det_M = np.linalg.det(M)
    print("\nb)")
    print("Định thức của M =", round(det_M, 3))
else:
    print("\nb)")
    print("Không thể tính định thức vì M không phải là ma trận vuông.")



b)
Định thức của M = 0.0


In [6]:
rank_N = np.linalg.matrix_rank(N)
print("\nc)")
print("Hạng của ma trận N =", rank_N)



c)
Hạng của ma trận N = 2


In [8]:
import numpy as np

P = np.array([
    [2, 1, 0, 1],
    [0, 3, 1, -1],
    [1, 0, 4, 2],
    [0, 1, 0, 3]
])

try:
    P_inv = np.linalg.inv(P)
    print("a)")
    print("Ma trận nghịch đảo của P là:\n", P_inv)
except np.linalg.LinAlgError:
    print("a)")
    print("Ma trận P không khả nghịch (không có ma trận nghịch đảo).")


a)
Ma trận nghịch đảo của P là:
 [[ 0.48837209 -0.09302326  0.02325581 -0.20930233]
 [ 0.03488372  0.27906977 -0.06976744  0.12790698]
 [-0.11627907  0.06976744  0.23255814 -0.09302326]
 [-0.01162791 -0.09302326  0.02325581  0.29069767]]


In [9]:
b = np.array([4, 7, 9, 5])
x = np.dot(P_inv, b)
print("\nb)")
print("Nghiệm của hệ phương trình là:\n", x)


b)
Nghiệm của hệ phương trình là:
 [0.46511628 2.10465116 1.65116279 0.96511628]


In [10]:
check = np.dot(P, x)
print("\nc)")
print("Kiểm tra P * x =\n", check)
print("Vector hằng số b =", b)


c)
Kiểm tra P * x =
 [4. 7. 9. 5.]
Vector hằng số b = [4 7 9 5]


In [11]:
import numpy as np

Q = np.array([
    [4, -1, 0],
    [1, 3, -2],
    [0, 1, 2]
])

eigenvalues, eigenvectors = np.linalg.eig(Q)

print("a)")
print("Các giá trị riêng của Q là:\n", eigenvalues)

a)
Các giá trị riêng của Q là:
 [3.45339765+0.j         2.77330117+1.46771151j 2.77330117-1.46771151j]


In [12]:

print("\nb)")
print("Các vector riêng (cột) tương ứng với các giá trị riêng là:\n", eigenvectors)


b)
Các vector riêng (cột) tương ứng với các giá trị riêng là:
 [[ 0.83327121+0.j         -0.26206044-0.31354813j -0.26206044+0.31354813j]
 [ 0.455468  +0.j         -0.78166743+0.j         -0.78166743-0.j        ]
 [ 0.31338154+0.j         -0.21963176+0.41685708j -0.21963176-0.41685708j]]


In [13]:
normed_vectors = eigenvectors / np.linalg.norm(eigenvectors, axis=0)

print("\nc)")
print("Các vector riêng sau khi chuẩn hóa là:\n", normed_vectors)



c)
Các vector riêng sau khi chuẩn hóa là:
 [[ 0.83327121+0.j         -0.26206044-0.31354813j -0.26206044+0.31354813j]
 [ 0.455468  +0.j         -0.78166743+0.j         -0.78166743+0.j        ]
 [ 0.31338154+0.j         -0.21963176+0.41685708j -0.21963176-0.41685708j]]


In [14]:
import numpy as np

R = np.array([
    [1, -2, 3],
    [2, 0, 1],
    [-1, 1, 4]
])

b = np.array([10, 8, 7])

x = np.linalg.solve(R, b)
print("a)")
print("Nghiệm x của hệ phương trình là:\n", x)

a)
Nghiệm x của hệ phương trình là:
 [2.7826087  0.04347826 2.43478261]


In [16]:
if np.linalg.det(R) != 0:
    R_inv = np.linalg.inv(R)
    x2 = np.dot(R_inv, b)
    print("\nb)")
    print("Ma trận R khả nghịch.")
    print("Nghiệm x tính bằng R⁻¹ * b là:\n", x2)
else:
    print("\nb)")
    print("Ma trận R không khả nghịch.")




b)
Ma trận R khả nghịch.
Nghiệm x tính bằng R⁻¹ * b là:
 [2.7826087  0.04347826 2.43478261]


In [17]:
fro_norm = np.linalg.norm(R, ord='fro')
print("\nc)")
print("Chuẩn Frobenius của R là:", round(fro_norm, 3))


c)
Chuẩn Frobenius của R là: 6.083
