In [1]:
import numpy as np
from numpy.linalg import norm
from math import acos, degrees

# Dữ liệu
A = np.array([3, -2, 1, 4])
B = np.array([-1, 5, 0, 2])
C = np.array([
    [2, -1, 3],
    [1, 4, -2],
    [0, 2, 5]
])

# Câu a
tong_AB = A + B
tich_so = 2 * A + 3 * B

print("Câu a:")
print("A + B =", tong_AB)
print("2A + 3B =", tich_so)

# Câu b
tich_vo_huong = np.dot(A, B)
cos_theta = tich_vo_huong / (norm(A) * norm(B))
goc_do = degrees(acos(cos_theta))

print("\nCâu b:")
print("Tích vô hướng A·B =", tich_vo_huong)
print("Góc giữa hai vector (độ) =", round(goc_do, 3))

# Câu c
C_CT = C @ C.T

print("\nCâu c:")
print("C * C^T =\n", C_CT)


Câu a:
A + B = [2 3 1 6]
2A + 3B = [ 3 11  2 14]

Câu b:
Tích vô hướng A·B = -5
Góc giữa hai vector (độ) = 99.594

Câu c:
C * C^T =
 [[14 -8 13]
 [-8 21 -2]
 [13 -2 29]]


In [2]:
import numpy as np

# Khai báo ma trận
M = np.array([
    [2, -1, 3, 0],
    [1, 4, -2, 5],
    [0, 2, 6, -3],
    [-1, 0, 1, 4]
])

N = np.array([
    [1, 3, -2, 0],
    [4, -1, 5, 2],
    [0, 2, 3, -1],
    [-3, 1, 0, 4]
])

# ===== a) Tích ma trận M x N =====
MN = M @ N  # hoặc np.dot(M, N)

print("=== Câu a ===")
print("Ma trận M × N:")
print(MN)

# ===== b) Định thức của ma trận M =====
det_M = np.linalg.det(M)

print("\n=== Câu b ===")
print("Định thức của ma trận M =", round(det_M, 3))

# Kiểm tra nếu gần bằng 0 thì không khả nghịch
if np.isclose(det_M, 0):
    print("→ Ma trận M không khả nghịch, định thức = 0.")
else:
    print("→ Ma trận M khả nghịch.")

# ===== c) Hạng của ma trận N =====
rank_N = np.linalg.matrix_rank(N)

print("\n=== Câu c ===")
print("Hạng của ma trận N =", rank_N)


=== Câu a ===
Ma trận M × N:
[[ -2  13   0  -5]
 [  2   0  12  30]
 [ 17   7  28 -14]
 [-13   3   5  15]]

=== Câu b ===
Định thức của ma trận M = 409.0
→ Ma trận M khả nghịch.

=== Câu c ===
Hạng của ma trận N = 4


In [3]:
import numpy as np

# Ma trận hệ số
P = np.array([
    [3, -1, 0, 2],
    [1, 4, -2, 0],
    [0, 1, 5, -1],
    [2, 0, 1, 3]
])

# Vector hằng số (vế phải)
b = np.array([6, 8, 3, 7])

# ===== a) Tìm ma trận nghịch đảo của P =====
print("=== Câu a ===")

det_P = np.linalg.det(P)
print("Định thức của P =", round(det_P, 3))

if np.isclose(det_P, 0):
    print("→ Ma trận P không khả nghịch (định thức = 0).")
    P_inv = None
else:
    P_inv = np.linalg.inv(P)
    print("Ma trận nghịch đảo P⁻¹:")
    print(np.round(P_inv, 3))

# ===== b) Giải hệ phương trình bằng nghịch đảo =====
print("\n=== Câu b ===")

if P_inv is not None:
    x = P_inv @ b
    print("Nghiệm của hệ phương trình [x, y, z, w] là:")
    print(np.round(x, 3))
else:
    print("Không giải được hệ bằng phương pháp nghịch đảo vì P không khả nghịch.")

# ===== c) Kiểm tra nghiệm bằng cách thế lại: P @ x == b =====
print("\n=== Câu c ===")

if P_inv is not None:
    check = P @ x
    print("Tích P · x:")
    print(np.round(check, 3))
    print("So sánh với vector b:")
    print(b)
    if np.allclose(check, b):
        print("✅ Nghiệm chính xác.")
    else:
        print("❌ Nghiệm sai.")


=== Câu a ===
Định thức của P = 140.0
Ma trận nghịch đảo P⁻¹:
[[ 0.5    0.1    0.1   -0.3  ]
 [-0.143  0.2    0.057  0.114]
 [-0.036 -0.05   0.164  0.079]
 [-0.321 -0.05  -0.121  0.507]]

=== Câu b ===
Nghiệm của hệ phương trình [x, y, z, w] là:
[2.    1.714 0.429 0.857]

=== Câu c ===
Tích P · x:
[6. 8. 3. 7.]
So sánh với vector b:
[6 8 3 7]
✅ Nghiệm chính xác.


In [6]:
import numpy as np

# Ma trận Q
Q = np.array([
    [5, -2, 1],
    [0, 3, -1],
    [2, 0, 4]
])

# Tính giá trị riêng và vector riêng
eigenvalues, eigenvectors = np.linalg.eig(Q)

print("=== Câu a ===")
print("Giá trị riêng (chỉ phần thực):")
for i, val in enumerate(eigenvalues):
    print(f"λ{i+1} =", np.round(val.real, 3))  # chỉ lấy phần thực

print("\n=== Câu b ===")
print("Vector riêng tương ứng (chỉ phần thực):")
for i, vec in enumerate(eigenvectors.T):  # Transpose để duyệt từng vector riêng
    vec_real = np.real(vec)  # loại bỏ phần ảo
    print(f"Vector riêng λ{i+1}: {np.round(vec_real, 3)}")

print("\n=== Câu c ===")
print("Vector riêng sau khi chuẩn hóa (chỉ phần thực):")
for i, vec in enumerate(eigenvectors.T):
    norm = np.linalg.norm(vec)  # chuẩn dài vector
    vec_norm_real = np.real(vec / norm)  # chia rồi lấy phần thực
    print(f"Vector λ{i+1} (chuẩn hóa): {np.round(vec_norm_real, 3)}")


=== Câu a ===
Giá trị riêng (chỉ phần thực):
λ1 = 6.355
λ2 = 2.822
λ3 = 2.822

=== Câu b ===
Vector riêng tương ứng (chỉ phần thực):
Vector riêng λ1: [ 0.748 -0.189  0.636]
Vector riêng λ2: [-0.374  0.095  0.636]
Vector riêng λ3: [-0.374  0.095  0.636]

=== Câu c ===
Vector riêng sau khi chuẩn hóa (chỉ phần thực):
Vector λ1 (chuẩn hóa): [ 0.748 -0.189  0.636]
Vector λ2 (chuẩn hóa): [-0.374  0.095  0.636]
Vector λ3 (chuẩn hóa): [-0.374  0.095  0.636]


In [7]:
import numpy as np

# Khai báo ma trận R và vector b
R = np.array([
    [4, -1, 2],
    [1, 3, -2],
    [0, 2, 5]
])
b = np.array([12, 5, 9])

# ===== a) Giải hệ Rx = b bằng np.linalg.solve() =====
print("=== Câu a ===")
x_direct = np.linalg.solve(R, b)
print("Nghiệm x (giải trực tiếp):", np.round(x_direct, 3))

# ===== b) Kiểm tra khả nghịch và dùng nghịch đảo để giải lại =====
print("\n=== Câu b ===")
det_R = np.linalg.det(R)
print("Định thức của R =", round(det_R, 3))

if np.isclose(det_R, 0):
    print("→ Ma trận R không khả nghịch.")
else:
    R_inv = np.linalg.inv(R)
    print("Ma trận nghịch đảo R⁻¹:")
    print(np.round(R_inv, 3))

    # Giải lại hệ: x = R⁻¹ · b
    x_inverse = R_inv @ b
    print("Nghiệm x (giải bằng nghịch đảo):", np.round(x_inverse, 3))

    # So sánh hai nghiệm
    if np.allclose(x_direct, x_inverse):
        print("✅ Hai nghiệm giống nhau.")
    else:
        print("❌ Hai nghiệm khác nhau.")

# ===== c) Chuẩn Frobenius của R =====
print("\n=== Câu c ===")
fro_norm = np.linalg.norm(R, ord='fro')
print("Chuẩn Frobenius của R =", round(fro_norm, 3))


=== Câu a ===
Nghiệm x (giải trực tiếp): [2.788 1.529 1.188]

=== Câu b ===
Định thức của R = 85.0
Ma trận nghịch đảo R⁻¹:
[[ 0.224  0.106 -0.047]
 [-0.059  0.235  0.118]
 [ 0.024 -0.094  0.153]]
Nghiệm x (giải bằng nghịch đảo): [2.788 1.529 1.188]
✅ Hai nghiệm giống nhau.

=== Câu c ===
Chuẩn Frobenius của R = 8.0
